Controllers/PanierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AjcProject.Models;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AjcProject.Controllers
{
    public class PanierController : Controller
    {
        private readonly AjcProjectDbContext _context;

        public PanierController(AjcProjectDbContext context)
        {
            _context = context;
        }

        // GET: CartItems
        public async Task<IActionResult> Index()
        {

            //Pour renvoyer l'id du panier
            var cartId = GetCartId();

            //Je vais chercher ma liste de cartItem avec une jointure sur le produit
            var ajcProjectDbContext = _context.CartItems.Include(c => c.Product).Where(c => c.CartId == cartId);
            var liste = await ajcProjectDbContext.ToListAsync();

            //Je calcule le montant total du panier
            ViewData["MontantTotal"] = liste.Sum(item => item.PrixTotal);

            //Je teste si la quantité des articles du panier est sup à zéro pour mettre le bouton valider en visible
            ViewData["btnVisible"] = (liste.Sum(item => item.Quantity) > 0);

            //Pour renvoyer l'id du panier
            ViewData["id"] = cartId;

            return View(liste);
        }

        // POST: CartItems
        [HttpPost]
        public async Task<IActionResult> Recalculer(List<CartItem> cartItemList)
        {
            //Supp des item du panier
            var ListToDelete = cartItemList.Where(item => item.ToDelete).ToList();
            _context.CartItems.RemoveRange(ListToDelete);

            //Mise à jour des qté item dans le panier
            var listToUpdate = cartItemList.Where(item => item.ToDelete == false).ToList();
            listToUpdate.ForEach(item => UpdateQteItem(item.ItemId, item.Quantity));

            //Verif si qté inf ou égal à 0
            for (int i = 0; i < listToUpdate.Count; i++)
            {
                if (listToUpdate[i].Quantity <= 0 )
                {
                    return RedirectToAction("Index");
                }
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private void UpdateQteItem(String itemId, int quantite)
        {
            var MyItem = _context.CartItems.FirstOrDefault(i => i.ItemId == itemId);
            if (MyItem != null && MyItem.Quantity != quantite)
            {
                MyItem.Quantity = quantite;
            }
        }

        private string GetCartId()
        {
            //Pas de temps pour générer un id panier pour chaque session donc juste un random
            return "6afd9c0b-4009-4723-a719-fcb9e200db35";
        }

        //methode add product
        public async Task<IActionResult> AddProduct(int id)
        {
            var product = _context.Products.Find(id);
            if (product == null)
            {
                // Return error message or redirect to appropriate page
                return RedirectToAction("Index");
            }

            var cartItem = _context.CartItems.FirstOrDefault(i => i.ProductId == id);
            if (cartItem != null)
            {
                cartItem.Quantity++;
            }
            else
            {
                cartItem = new CartItem
                {
                    ProductId = id,
                    Quantity = 1,
                    ItemId = System.Guid.NewGuid().ToString(),
                    DateCreated = DateTime.Now,
                    CartId = GetCartId()
                };
                _context.Add(cartItem);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }

}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AjcProject.Models;

namespace AjcProject.Controllers
{
    public class ProductController : Controller
    {
        private readonly AjcProjectDbContext _context;

        public ProductController(AjcProjectDbContext context)
        {
            _context = context;
        }

        // GET: Product/SearchString="Nom des produits", Searchcategory="Categories des produits", SearchNombreMax = "Prix max des produits"
        public async Task<IActionResult> Index(string SearchString, string Searchcategory,double SearchNombreMax)
        {
            ViewData["category"] = "Toutes les catégories";

            //Recuperation et injection de la liste des categories dans le viewdata "ListCategory"
            ViewData["ListCategory"] = _context.Categories.ToList().OrderBy(p => p.CategoryName);

            //Check si la list des produits n'est pas vide
            if (_context.Products == null)
            {
                return Problem("L'entite '_context.Categories' est null.");
            }
            //Recuperation de la list des produits
            var ajcProjectDbContext = _context.Products.Include(p => p.Category);

            //Recherche par Nom des produits
            if (!String.IsNullOrEmpty(SearchString))
            {
                ajcProjectDbContext = ajcProjectDbContext.Where(s => s.ProductName!.Contains(SearchString)).Include(p => p.Category);
            }

            //Recherche par Categories
            if (!String.IsNullOrEmpty(Searchcategory) && (Searchcategory != "Toutes les catégories"))
            {
                ViewData["category"] = Searchcategory;
                ajcProjectDbContext = ajcProjectDbContext.Where(s => s.Category.CategoryName!.Contains(Searchcategory)).Include(p => p.Category);
            }

            //Recherche par Prix max
            if (SearchNombreMax > 0)
            {
                ajcProjectDbContext = ajcProjectDbContext.Where(s => s.UnitPrice! <= SearchNombreMax).Include(p => p.Category);
            }
            return View(await ajcProjectDbContext.ToListAsync());
        }

        // GET: Product/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }
    }
}

Views/Shared/CategMenu.cshtml
@*Dépendances pour request SQL*@
@using System.Linq
@using System.Threading.Tasks

@*Injection du context de la base de donnée*@
@inject AjcProject.Models.AjcProjectDbContext _dbContext
@{
    @*Creation de la liste contenant les categories de produits*@

    var list = _dbContext.Categories.OrderBy(p => p.CategoryName).ToList();

    @*Variable utilise pour ne pas la balise Span lors de la premiere iteration de la boucle*@
    var count = 1;
}
@*Boucle ajoutant au html les noms des categories*@
@foreach (var item in list)
{

    @if (count > 1)
    {
        <span> | </span>
    }
    <a asp-controller="Product" asp-action="Index" asp-route-Searchcategory="@item.CategoryName">
        @Html.DisplayFor(modelItem => item.CategoryName)
    </a>

    count++;
}

Views/Shared/_CartItemCount.cshtml
@using System.Linq
@using System.Threading.Tasks
@inject AjcProject.Models.AjcProjectDbContext _dbContext
@{
    var list = _dbContext.CartItems.ToList();
    ViewData["countTotal"] = list.Sum(item => item.Quantity);
}
<a class="nav-link text-light" asp-area="" asp-controller="Panier" asp-action="Index">Panier(@ViewData["countTotal"])</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AjcProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="sticky-top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-custom bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Services Ordering Plateform</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">A propos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="Index">Nos services</a>
                        </li>
                       <li class="nav-item"><partial name="_CartItemCount.cshtml"/></li>

                        @{
                            if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item dropdown">
                                    <a href="#" class="nav-link dropdown-toggle text-light" data-toggle="dropdown">Administration (BackEnd) <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="~/AdminProduct/Index">Produits</a></li>
                                        <li><a class="dropdown-item" href="~/AdminCateg/Index">Catégories</a></li>
                                        <li class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" href="~/Users/Index">Utilisateurs</a></li>
                                        <li class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" href="~/OrderAdmin/Index">Commandes</a></li>
                                    </ul>
                                </li>
                            }

                        }
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between text-light">
                    <partial name="_LoginPartial.cshtml" />
                </div>
            </div>
        </nav>
    </header>


    <div class="container text-center">
        <!-- GROUPE 3   : Injecter -->
        <partial name="CategMenu.cshtml" />
    </div>
    <div class="container text-center">
        <img src="~/Images/logo.jpg" />
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AjcProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_ordersDetails.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model ICollection<AjcProject.Models.OrderDetail>
@{
}
<table class="tablelarge " cellspacing="0" cellpadding="10" rules="all"
       style="border-color:#317EAC;border-width:2px;border-style:solid;border-collapse:collapse;">

    <thead>
        <tr>
            <th>
                <label for="CartId">ID</label>
            </th>
            <th>
                <label for="ProductName">Service</label>
            </th>
            <th>
                <label for="UnitPrice">Prix unitaire</label>
            </th>
            <th>
                <label for="Quantity">Nombre</label>
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (OrderDetail item in Model)
        {
            <tr>
                @Html.HiddenFor(m => item.OrderDetailId)
                @Html.HiddenFor(m => item.OrderId)
                @Html.HiddenFor(m => item.ProductId)
                <td style="width:10%;">
                    @Html.DisplayFor(m => item.ProductId)
                </td>
                <td style="width:50%;">
                    @Html.DisplayFor(m => item.ProductName)
                </td>
                <td style="width:15%;">
                    @String.Format("{0:c}", item.UnitPrice)
                </td>
                <td style="width:15%;" class="text-center">
                    @Html.DisplayFor(m => item.Quantity)
                </td>
            </tr>
        }
    </tbody>
</table>