Controllers/AdminProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AjcProject.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Linq.Expressions;
using System.Net.Mime;
using System.Drawing;
using System.Net;
using static System.Net.Mime.MediaTypeNames;
using Microsoft.AspNetCore.Authorization;

namespace AjcProject.Controllers
{
    [Authorize]
    public class AdminProductController : Controller
    {
        private readonly AjcProjectDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly long _fileSizeLimit;
        private readonly string[] _permittedExtensions = { "image/jpeg", "image/png", "image/gif", "image/svg+xml" };

        private readonly IDateTime _dateTime;
        private readonly IRandomCode _rand;

        public AdminProductController(AjcProjectDbContext context, IWebHostEnvironment hostEnvironment, IConfiguration config, IDateTime dateTime, IRandomCode rand)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
            _fileSizeLimit = config.GetValue<long>("FileSizeLimit");
            _dateTime = dateTime;
            _rand = rand;
        }

        // GET: AdminProduct
        public async Task<IActionResult> Index()
        {
            var ajcProjectDbContext = _context.Products.Include(p => p.Category);
            return View(await ajcProjectDbContext.ToListAsync());
        }

        // GET: AdminProduct/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: AdminProduct/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");
            return View();
        }

        // POST: AdminProduct/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,Description,ImagePath,UnitPrice,CategoryId")] Product product)
        {

            if (ModelState.IsValid)
            {
                var prdReq = (from p in _context.Products
                              where p.ProductName.Contains(product.ProductName)
                              select p).Any();

                if (prdReq)
                {

                    ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
                    ViewData["error"] += "Ce nom de service existe déjà !";
                    return View(product);
                }

                if (Request.Form.Files.Any())
                {
                    IFormFile file = Request.Form.Files[0];
                    string ctType = file.ContentType;
                    long filelength = file.Length;
                    string fileName = WebUtility.HtmlEncode(file.FileName);
                    string extension = Path.GetExtension(fileName).ToLowerInvariant();


                    if (string.IsNullOrEmpty(ctType) || !_permittedExtensions.Contains(ctType))
                    {
                        ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
                        ViewData["error"] += "Type de fichier non autorisé";
                        return View(product);
                    }


                    if (filelength > _fileSizeLimit)
                    {
                        ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
                        ViewData["error"] += "Fichier trop volumineux !";
                        return View(product);
                    }

                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    fileName = _rand.RndCode + DateTime.Now.ToFileTime();
                    product.ImagePath = WebUtility.HtmlEncode(fileName + extension);
                    string path = Path.Combine(wwwRootPath, "Catalog", "images");
                    var downloadResult = Download(file, path, fileName + extension);
                }

                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            return View(product);
        }

        // GET: AdminProduct/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var product = await _context.Products.FindAsync(id);


            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            return View(product);
        }

        // POST: AdminProduct/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,Description,ImagePath,UnitPrice,CategoryId")] Product product)
        {

            if (id != product.ProductId)
            {
                return NotFound();
            }

            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);

            if (ModelState.IsValid)
            {
                var sameService = _context.Products.FirstOrDefault(prod => prod.ProductId != id
                && prod.ProductName == product.ProductName);

                if (sameService != null)
                {
                    ViewData["error"] += "Ce nom de service existe déjà !";
                    return View(product);
                }
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }



            if (Request.Form.Files.Any())
            {
                IFormFile file = Request.Form.Files[0];
                string ctType = file.ContentType;
                long filelength = file.Length;
                string fileName = WebUtility.HtmlEncode(file.FileName);
                string extension = Path.GetExtension(fileName).ToLowerInvariant();

                if (string.IsNullOrEmpty(ctType) || !_permittedExtensions.Contains(ctType))
                {
                    ViewData["error"] += "Type de fichier non autorisé";
                    return View(product);
                }
                if (filelength > _fileSizeLimit)
                {
                    ViewData["error"] += "Fichier trop volumineux !";
                    return View(product);
                }

                string wwwRootPath = _hostEnvironment.WebRootPath;
                fileName = _rand.RndCode + DateTime.Now.ToFileTime();
                product.ImagePath = fileName + extension;
                string path = Path.Combine(wwwRootPath, "Catalog", "images");

                var downloadResult = Download(file, path, fileName + extension);

            }

            try
            {
                _context.Update(product);
                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                return NotFound();
            }
            return RedirectToAction(nameof(Index));
        }


        // GET: AdminProduct/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: AdminProduct/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }

        public async Task<IActionResult> OrderByPriceAsc()
        {
            var list = _context.Products.OrderBy(produit => produit.UnitPrice).ToList();
            return View("Index", list);
        }
        public async Task<IActionResult> OrderByPricedesc()
        {
            var list = _context.Products.OrderByDescending(produit => produit.UnitPrice).ToList();

Views/AdminProduct/Create.cshtml
@model AjcProject.Models.Product

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var error = ViewData["error"];
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form id="registerForm" method="post" asp-controller="AdminProduct" asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" id="ProductName" name="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" id="Description" name="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                    <input asp-for="UnitPrice" id="UnitPrice" name = "UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" id="CategoryId" name="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                    <input asp-for="ImagePath" id="ImagePath" name="ImagePath" class="form-control" type="file" accept="image/*" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            @{
              
                if ((string)error !="")
                {
                                    <div class="alert-danger align-middle">
                                        @ViewData["error"]
                                    </div>
                }
            }

            <div class="form-group">
                    <input id="create" type="submit" value="Create" class="btn btn-primary "  data-target="#exampleModalCenter" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Views/AdminProduct/Delete.cshtml
@model AjcProject.Models.Product

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/AdminProduct/Details.cshtml
@model AjcProject.Models.Product

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProductId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/AdminProduct/Edit.cshtml
@model AjcProject.Models.Product

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var error = ViewData["error"];
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger" disabled></div>
            <input type="hidden" asp-for="ProductId" />
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                @*l'attribut image permet de n'accepter que des fichiers images dans l'explorateur de fichiers*@
                <input asp-for="ImagePath" class="form-control" type="file" accept="image/*" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            @{

                if ((string)error != "")
                {
                    <div class="alert-danger align-middle">
                        @ViewData["error"]
                    </div>
                }
            }

            <div class="form-group">
                @{
                    if (Model.ImagePath != null)
                    {
                        <img alt="@Html.DisplayFor(modelItem => Model.ProductName)"
                         class="card-img-top" src="/Catalog/Images/@Model.ImagePath">
                    }
                }

            </div>


            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/AdminProduct/Index.cshtml
@model IEnumerable<AjcProject.Models.Product>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UnitPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ImagePath)
                </td>
                <td>
                    <img alt="@Html.DisplayFor(modelItem => item.ProductName)"
                     class="card-img-top" src="/Catalog/Images/@item.ImagePath">
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.UnitPrice)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.Category.CategoryName)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ProductId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ProductId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ProductId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>