Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System;
using System.Linq;
using AjcProject.Models;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using AjcProject.Areas.Identity.Data;

namespace AjcProject.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {


        private readonly AjcProjectDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public OrderController(AjcProjectDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        // GET: OrderController
        [Route("Index/{idPanier}")]
        public async Task<IActionResult> Index(string idPanier)
        {

            List<CartItem> CartItems = _context.CartItems.Include(p => p.Product).Where(
                c => c.CartId == idPanier).ToList();


            Order order = new Order();

            if (User.Identity.IsAuthenticated)
            {
                var user = await _userManager.GetUserAsync(User);
                order.Username = user.UserName;
                order.Email = user.Email;
                order.FirstName = user.FirstName;
                order.LastName = user.LastName;
            }

            //Calcul du total
            order.Total = Convert.ToDecimal(CartItems.Sum(item => item.PrixTotal));

            foreach (CartItem item in CartItems)
            {
                item.Product = _context.Products.Where(p => p.ProductId == item.ProductId).ToList()[0];

                OrderDetail detail = new OrderDetail()
                {
                    OrderId = order.OrderId,

                    ProductId = item.ProductId,
                    Quantity = item.Quantity,
                    UnitPrice = item.Product.UnitPrice,
                    Username = order.Username,
                    // Attirer l'attention du stagiaires ici sur le NotMapped
                    // car le nom du produit, on en a besoin uniquement
                    // pour l'afficher dans la liste des détails
                    // de commande
                    ProductName = item.Product.ProductName
                };
                order.OrderDetails.Add(detail);
            }


            _context.Add(order);
            _context.SaveChanges();

            ViewData["CartID"] = idPanier;

            return View(order);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(string idPanier, [Bind("OrderId,FirstName,LastName,Address,City,Country,PostalCode,Total,Username,Email")] Order order)
        {
            order.OrderDate = DateTime.Now;

            DeleteCart(idPanier);

            string Pid = System.Guid.NewGuid().ToString();
            order.PaymentTransactionId = Pid;

            _context.Orders.Update(order);
            _context.SaveChanges();

            return View(order);
        }

        private void DeleteCart(string id)
        {
            List<CartItem> CartItems = _context.CartItems.Where(
                c => c.CartId == id).ToList();

            foreach (CartItem item in CartItems)
            {
                _context.Remove(item);
            }
        }

    }
}

Controllers/PanierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AjcProject.Models;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AjcProject.Controllers
{
    public class PanierController : Controller
    {
        private readonly AjcProjectDbContext _context;

        public PanierController(AjcProjectDbContext context)
        {
            _context = context;
        }

        // GET: CartItems
        public async Task<IActionResult> Index()
        {

            //Pour renvoyer l'id du panier
            var cartId = GetCartId();

            //Je vais chercher ma liste de cartItem avec une jointure sur le produit
            var ajcProjectDbContext = _context.CartItems.Include(c => c.Product).Where(c => c.CartId == cartId);
            var liste = await ajcProjectDbContext.ToListAsync();

            //Je calcule le montant total du panier
            ViewData["MontantTotal"] = liste.Sum(item => item.PrixTotal);

            //Je teste si la quantité des articles du panier est sup à zéro pour mettre le bouton valider en visible
            ViewData["btnVisible"] = (liste.Sum(item => item.Quantity) > 0);

            //Pour renvoyer l'id du panier
            ViewData["id"] = cartId;

            return View(liste);
        }

        // POST: CartItems
        [HttpPost]
        public async Task<IActionResult> Recalculer(List<CartItem> cartItemList)
        {
            //Supp des item du panier
            var ListToDelete = cartItemList.Where(item => item.ToDelete).ToList();
            _context.CartItems.RemoveRange(ListToDelete);

            //Mise à jour des qté item dans le panier
            var listToUpdate = cartItemList.Where(item => item.ToDelete == false).ToList();
            listToUpdate.ForEach(item => UpdateQteItem(item.ItemId, item.Quantity));

            //Verif si qté inf ou égal à 0
            for (int i = 0; i < listToUpdate.Count; i++)
            {
                if (listToUpdate[i].Quantity <= 0 )
                {
                    return RedirectToAction("Index");
                }
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private void UpdateQteItem(String itemId, int quantite)
        {
            var MyItem = _context.CartItems.FirstOrDefault(i => i.ItemId == itemId);
            if (MyItem != null && MyItem.Quantity != quantite)
            {
                MyItem.Quantity = quantite;
            }
        }

        private string GetCartId()
        {
            //Pas de temps pour générer un id panier pour chaque session donc juste un random
            return "6afd9c0b-4009-4723-a719-fcb9e200db35";
        }

        //methode add product
        public async Task<IActionResult> AddProduct(int id)
        {
            var product = _context.Products.Find(id);
            if (product == null)
            {
                // Return error message or redirect to appropriate page
                return RedirectToAction("Index");
            }

            var cartItem = _context.CartItems.FirstOrDefault(i => i.ProductId == id);
            if (cartItem != null)
            {
                cartItem.Quantity++;
            }
            else
            {
                cartItem = new CartItem
                {
                    ProductId = id,
                    Quantity = 1,
                    ItemId = System.Guid.NewGuid().ToString(),
                    DateCreated = DateTime.Now,
                    CartId = GetCartId()
                };
                _context.Add(cartItem);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }

}

Views/Panier/Index.cshtml
@model List<AjcProject.Models.CartItem>

@{
    ViewData["Title"] = "Index";
}
<form method="post" asp-controller="Panier" asp-action="Recalculer">
    <h1 class="text-primary">Votre panier :</h1>
    <div class="container-fluid">
        <table class="table table-bordered table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col" class="text-center">
                        <label for="CartId">ID</label>
                    </th>
                    <th scope="col">
                        <label for="ProductName">Produit</label>
                    </th>
                    <th scope="col">
                        <label for="UnitPrice">Tarif</label>
                    </th>
                    <th scope="col">
                        <label for="Quantity">Quantité</label>
                    </th>
                    <th scope="col">
                        <label for="UnitPrice">Prix Total</label>
                    </th>
                    <th scope="col">
                        <label>Supprimer</label>
                    </th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Count(); i++)
                {

                    <tr>
                        @Html.HiddenFor(m => m[i].CartId)
                        @Html.HiddenFor(m => m[i].ItemId)
                        @Html.HiddenFor(m => m[i].ProductId)

                        <td class="text-center">
                            @Html.DisplayFor( m => m[i].Product.ProductId)

                        <td>
                            @Html.DisplayFor(m => m[i].Product.ProductName)
                        </td>
                        <td>
                            @String.Format("{0:c}",Model[i].Product.UnitPrice)
                        </td>
                        <td class="text-center">
                                @Html.TextBoxFor(m => m[i].Quantity, new { style = "width: 40px;" })
                        </td>
                        <td>
                            @String.Format("{0:c}", Model[i].PrixTotal)
                        </td>
                        <td class="text-center">
                                @Html.CheckBoxFor(m => m[i].ToDelete, new { style = "height: 30px; width: 30px;" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <div class="p-2">
            <span id="MainContent_LabelTotalText">
                Montant Total :
            </span>
            <strong>
                <span id="MainContent_lblTotal">@String.Format("{0:c}",ViewData["MontantTotal"])</span>
            </strong>
        </div>
        <div class="row">
            <div class="col-auto mr-auto">
                <input type="submit" name="recalculer" value="Recalculer" id="maincontent_updatebtn" class="btn btn-primary">
            </div>
            <div class="col-auto">
                <a class="btn btn-primary" href="/Product">Continuer mes achats</a>
            </div>
            <div class="col-auto">
                @{
                    if ((bool)ViewData["btnVisible"])
                    {
                        <a class="btn btn-success" asp-controller="Order" asp-action="Index" asp-route-idPanier="@ViewData["id"]">
                            Valider
                        </a>
                    }
                }
            </div>
        </div>
    </div>
</form>